### PR TITLE
Added icon to title bar in base, contact, and esmd_replacment pages...

### PR DESCRIPTION
**Pull request by mike-u**
I made an icon from the Design Hub logo to go in the title bar instead of the generic page icon. I tried each of the 4 little drawings and the pencil rocket turned out the best.

### CODE REVIEW

**Comment by ianpmc** [comment]
Thank you! I've been meaning to add this. We'll be moving the contact and esmd replacement html files to the Jinja2 templating convention soon, but you got base.html and that's what matters.

**Comment by ianpmc** [comment]
It's live on the site now

**Comment by ianpmc** [comment]
I also put your name in the footer as a contributor

**Comment by mike-u** [comment]
?Cool, thanks! Is there a list of other things that need to be done?


Michael Urich
University of Pittsburgh
________________________________

**Comment by ianpmc** [comment]
There's a TODO list in the GitHub wiki. It's kind of sparse, but it has a
few things that could be nice to have. Feel free to add your own flair!
I'll start keeping it up to date.

**Pull request merged**
